name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
  workflow_dispatch: # Manual trigger

jobs:
  publish:
    name: publish nugets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
          source-url: https://nuget.pkg.github.com/arawnik/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN }}
      - name: Build Solution
        run: dotnet build --configuration Release
      - name: Pack Common
        run: dotnet pack src/SoulNETLib.Common/SoulNETLib.Common.csproj --output nuget-packages --configuration Release
      - name: Pack EFCore
        run: dotnet pack src/SoulNETLib.EFCore/SoulNETLib.EFCore.csproj --output nuget-packages --configuration Release
      - name: Pack Clean architecture Common
        run: dotnet pack src/SoulNETLib.Clean.Domain/SoulNETLib.Clean.Domain.csproj --output nuget-packages --configuration Release
      - name: Pack Clean architecture Application
        run: dotnet pack src/SoulNETLib.Clean.Application/SoulNETLib.Clean.Application.csproj --output nuget-packages --configuration Release
      - name: Push packages to GitHub Packages
        run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/arawnik/index.json --api-key ${{ secrets.PACKAGES_TOKEN }} --skip-duplicate