name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: publish nugets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/sawyl/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
      - name: Build Solution
        run: dotnet build --configuration Release
      - name: Pack Common
        run: dotnet pack SoulNETLib.Common/SoulNETLib.Common.csproj --output nuget-packages --configuration Release
      - name: Pack EFCore
        run: dotnet pack SoulNETLib.EFCore/SoulNETLib.EFCore.csproj --output nuget-packages --configuration Release
      - name: Push
        run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{env.NUGET_AUTH_TOKEN}} --source https://nuget.pkg.github.com/sawyl/index.json